backend:
  name: github
  repo: quicklab-tech/quicklab.tech
  branch: main
  base_url: https://site-movisul.vercel.app
  auth_endpoint: /api/auth

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
